FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    gdb \
    git \
    libboost-all-dev \
    libsqlite3-dev \
    nlohmann-json3-dev \
    libgtest-dev \
    libgmock-dev \
    && rm -rf /var/lib/apt/lists/*

# Build GTest
RUN cd /usr/src/googletest && \
    cmake . && \
    cmake --build . --target install
